# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'YJViewControllerTransitioning' do
  pod 'YJCocoa/AppFrameworks/UIKit/ViewControllerTransitioning' , :path => "../../../../YJCocoaOC.podspec"
end
