# Uncomment this line to define a global platform for your project
platform :ios, '6.0'
# Uncomment this line if you're using Swift
# use_frameworks!

#pod 'YJCocoa/CocoaTouchLayer/UIKit/ViewGeometry'
#pod 'YJCocoa/CocoaTouchLayer/UIKit/AutoLayout'
#pod 'YJCocoa/CoreServicesLayer/Foundation/Other'
#pod 'YJCocoa/CoreOSLayer/System'

pod 'YJCocoa', :git => 'https://github.com/937447974/YJCocoa.git', :branch =>'developer' #开发环境
