# Uncomment this line to define a global platform for your project
platform :ios, '7.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'YJPageView' do
    pod 'YJCocoa/AppFrameworks/UIKit/AutoLayout'
    pod 'YJCocoa/AppFrameworks/Foundation/Other'
end
