# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

pod 'YJCocoa', :git => 'https://github.com/937447974/YJCocoa.git', :branch => 'developer'

#pod 'YJCocoa/CoreServicesLayer/Foundation/Log'

