platform :ios, '9.0'
use_frameworks!

target 'YJCodeInject' do
  pod 'YJCocoa/OC/CodeInject', :path => "../../../YJCocoa.podspec"
  pod 'FrameworkA', :path => "./FrameworkA/"
  pod 'FrameworkB', :path => "./FrameworkB/"
end
