# Uncomment the next line to define a global platform for your project
platform :ios, '7.0'

target 'YJLeaks' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YJLeaks

    pod 'YJCocoa/System/Dispatch'

end
