# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

def shared_pods
    pod 'YJCocoa/AppFrameworks/UIKit/ScrollViewManager', :path => "../../../../YJCocoa.podspec"
end

target 'ScrollViewManager' do
    shared_pods
end

