# Uncomment the next line to define a global platform for your project
platform :ios, '7.0'

def shared_pods
    pod 'YJCocoa/AppFrameworks/Foundation/AOP'
    pod 'YJCocoa/AppFrameworks/UIKit/ViewGeometry'
end

target 'ScrollViewManager' do
    shared_pods
end

