# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!


def shared_pods
    pod 'YJCocoa/AppFrameworks/UIKit/CollectionViewManager', :path => "../../../../"
end

target 'YJCollectionView' do
    shared_pods
end

