# Uncomment this line to define a global platform for your project
platform :ios, '7.0'
# Uncomment this line if you're using Swift
# use_frameworks!

def shared_pods
    pod 'YJCocoa/System/Dispatch'
    pod 'YJCocoa/System/Security/Random'
#pod 'YJCocoa', :git => 'https://github.com/937447974/YJCocoa.git', :branch =>'developer' #开发环境
end

target 'YJFoundation' do
    shared_pods
end

target 'YJFoundationTests' do
    shared_pods
end
