# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

def shared_pods
   pod 'YJCocoa/AppFrameworks/Foundation', :path => "../../../YJCocoa.podspec", :inhibit_warnings => false
end

target 'YJFoundation' do
    shared_pods
    target 'YJFoundationTests' do
        inherit! :search_paths
    end
end


