# Uncomment this line to define a global platform for your project
platform :ios, '6.0'
# Uncomment this line if you're using Swift
# use_frameworks!

pod 'YJCocoa/System/Dispatch'
pod 'YJCocoa/System/Security/Random'

#pod 'YJCocoa', :git => 'https://github.com/937447974/YJCocoa.git', :branch =>'developer' #开发环境
