platform :ios, '9.0'
use_frameworks!
install! 'cocoapods', :disable_input_output_paths => true

target 'YJViewControllerTransitioning' do
    pod 'YJCocoa/AppFrameworks/UIKit/ViewControllerTransitioning', :path => "../../../../../YJCocoa.podspec"
end
