platform :ios, '9.0'
use_frameworks!
install! 'cocoapods', :disable_input_output_paths => true

target 'YJTimeline' do
    pod 'YJCocoa', :path => "../../../../YJCocoa.podspec"
    target 'YJTimelineTests' do
        inherit! :search_paths
        # Pods for testing
    end
end
