# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'YJScheduler' do
   pod 'YJCocoa/AppFrameworks/Foundation/Scheduler', :path => "../../../../YJCocoa.podspec"
end
