# Uncomment this line to define a global platform for your project
platform :ios, '6.0'
# Uncomment this line if you're using Swift
# use_frameworks!

pod 'YJCocoa/CoreServicesLayer/Foundation'
pod 'YJCocoa/CoreOSLayer/System'

target 'YJCollectionView' do

end

