# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YJTimeProfiler' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YJTimeProfiler
  pod 'YJCocoa/AppFrameworks/Foundation/Singleton'
  pod 'YJCocoa/AppFrameworks/Foundation/Swizzling'
  pod 'YJCocoa/System/Dispatch'
    
end
