# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'YJCoreData' do
    
    pod 'YJCocoa/AppServices/CoreData', :path => "../../../YJCocoa.podspec"
    pod 'YJCocoa/System/Dispatch', :path => "../../../YJCocoa.podspec"
    
end

