# Uncomment this line to define a global platform for your project
platform :ios, '7.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'YJCoreData' do

pod 'YJCocoa/AppFrameworks/Foundation/Directory'
pod 'YJCocoa/AppFrameworks/Foundation/FileManager'
pod 'YJCocoa/AppFrameworks/Foundation/Timer'
pod 'YJCocoa/System/Dispatch'

end

