platform :ios, '9.0'
use_frameworks!
install! 'cocoapods', :disable_input_output_paths => true

target 'YJSystem' do
    pod 'YJCocoa', :path => "../../../YJCocoa.podspec"
    target 'YJSystemTests' do
        inherit! :search_paths
        # Pods for testing
    end
end
