platform :ios, '9.0'
use_frameworks!
install! 'cocoapods', :disable_input_output_paths => true

target 'YJFoundation' do
    pod 'YJCocoa', :path => "../../../../../YJCocoa.podspec"
    target 'YJFoundationTests' do
        inherit! :search_paths
    end
end
